### ISSUE TITLE
Radio not working

### ISSUE THREAD

**Issue by KeenVox** [coreWeaver/RAC-the.Radio.Alarm.Clock#1]
Hey there,

I build your project and so far everything seems to work exceopt the radio. When I start the devices I get a constand buzzing noise from both speakers. I send some Radio station via UART but sadly it does not change anything. The volume pot does not change the noise volume. 
Any idead, where to start troubleshooting? Thank you!

**Comment by coreWeaver** [comment]
hey,
I would try using another radio module. I think the one you used it's not compatible with the firmware or it may be broken.
About the volume potentiometer not working, that's an audio amp IC related problem. make sure your TDA7052 is the "A" version. The "7052 without A" doesn't have a volume control pin.
